apiVersion: v2
name: sequin
description: Helm chart for Sequin with PostgreSQL and Redis
version: 0.2.0
type: application

maintainers:
  - name: Carter Pedersen
    email: carter.e.pedersen@gmail.com
    url: https://github.com/RTLS
  - name: Alexey Zhokhov
    email: alexey@zhokhov.com
    url: https://github.com/donbeave

dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: oci://registry-1.docker.io/bitnamichartslegacy
    version: 16.x.x
  - condition: redis.enabled
    name: redis
    repository: oci://registry-1.docker.io/bitnamichartslegacy
    version: 18.x.x
  - name: common
    repository: oci://registry-1.docker.io/bitnamichartslegacy
    tags:
      - bitnami-common
    version: 2.x.x

sources:
  - https://github.com/sequinstream/helm-chart-sequin
